### ISSUE TITLE
change sidebar into accordion with approp and cc

### ISSUE THREAD

**Issue by kwheelan** [CityOfDetroit/Departmental-Budget-Request-Form#66]
- [x]  Edit summary page to include collapsible CC and Approp info (#33)
 - [x] Add overtime as a separate rollup on sidebar and summary page
 - [x] Separate personnel costs accordingly
 - [ ] Alter sidebar to accordion
 - [x] #86
 - [ ] Add edit buttons on headers for each fund?
 - [ ] Add new nav button to return to summary or continue to XXXX
 - [x] Add lookup table for approp and cc labels

**Comment by katrina-cityofdetroit** [comment]
Closing for now
